I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 247, in script
    menu:
  File "game/script.rpy", line 254, in <module>
    "There is no ''Calling the police''." if loves_police == True:
NameError: name 'loves_police' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 247, in script
    menu:
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\ast.py", line 1632, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\exports\menuexports.py", line 100, in menu
    condition = renpy.python.py_eval(condition)
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\python.py", line 1215, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\FreeFromDrive\SaveYourDesktop\renpy-8.3.6-sdk\renpy\python.py", line 1208, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 254, in <module>
    "There is no ''Calling the police''." if loves_police == True:
NameError: name 'loves_police' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.6.25022803
DoesNotKommunisere 1.0
Tue Apr  1 09:31:39 2025
